name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

# Add permissions at the workflow level
permissions:
  id-token: write   # Required for OIDC authentication
  contents: write   # Required for checkout and artifact upload
  pages: write      # Required for deploying to GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
